#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../../.." && pwd)"
target_dir="$repo_root/artifacts/operations/baseline"
mkdir -p "$target_dir"

check=false
if [[ "${1:-}" == "--check" ]]; then
  check=true
  shift
fi
if [[ $# -ne 0 ]]; then
  echo "usage: $0 [--check]" >&2
  exit 64
fi

temp_root="${TMPDIR:-/tmp}"
out_dir="$(mktemp -d "${temp_root%/}/lenbands-repository-baseline.XXXXXX")"
trap 'rm -rf "$out_dir"' EXIT

capability_index="$repo_root/artifacts/operations/catalogs/capability-index.md"
phase_index="$repo_root/artifacts/operations/catalogs/capability-phase-index.md"

# family_for() resolved via canonical capability-family-map.yaml through CapabilityRegistry.
# No case statements — business knowledge lives in data.

has_file() {
  [[ -f "$repo_root/$1" ]] && echo present || echo missing
}

cat > "$out_dir/capability-baseline.md" <<EOF
# Repository Baseline — Capability Catalog

Generated by tools/generate-repository-baseline.sh from:

- artifacts/operations/catalogs/capability-index.md (projection of blueprint/03-features.md)
- artifacts/operations/catalogs/capability-phase-index.md (phase projection)
- artifacts/operations/capability-family-map.yaml (canonical capability→family mapping)

This report is diagnostic. It is not a capability or family source of truth.

| Metric | Value |
|---|---:|
| Total capability IDs | $(awk -F'|' '/^\| \x60[^\x60]+\x60 \|/ {n++} END {print n}' "$capability_index") |
| P0 | $(awk -F'|' '/^\| \x60[^\x60]+\x60 \| P0 \|/ {n++} END {print n+0}' "$phase_index") |
| P1 | $(awk -F'|' '/^\| \x60[^\x60]+\x60 \| P1 \|/ {n++} END {print n+0}' "$phase_index") |
| P2 | $(awk -F'|' '/^\| \x60[^\x60]+\x60 \| P2 \|/ {n++} END {print n+0}' "$phase_index") |
| Deferred | $(awk -F'|' '/^\| \x60[^\x60]+\x60 \| deferred \|/ {n++} END {print n+0}' "$phase_index") |
| Unknown IDs in catalog projection | not detected by this baseline generator; semantic validator required |
| Duplicate IDs | $(awk -F'|' '/^\| \x60[^\x60]+\x60 \|/ {print $2}' "$capability_index" | sort | uniq -d | wc -l | tr -d ' ') |

## Capability inventory

| Capability | Phase | Candidate family |
|---|---|---|
EOF

# Resolve family via canonical CapabilityRegistry (reads capability-family-map.yaml).
ruby -I"$repo_root/tools/lib" -rlenbands -rlenbands/registries - "$phase_index" "$capability_index" "$out_dir" <<'RUBY'
phase_index_path, capability_index_path, out_dir = ARGV

phase_lines = File.read(phase_index_path).lines

phase_for = lambda do |id|
  phase_lines.each do |line|
    parts = line.split("|").map(&:strip)
    next unless parts.length >= 3
    row_id = parts[1].to_s[/\A`([^`]+)`\z/, 1]
    next unless row_id == id
    return parts[2]
  end
  "unknown"
end

ids = File.read(capability_index_path)
  .scan(/^\| `([^`]+)` \|/)
  .flatten

File.open(File.join(out_dir, "capability-baseline.md"), "a") do |f|
  ids.each do |id|
    phase = phase_for.call(id)
    family = Lenbands::Registries::CapabilityRegistry.family_for(id) || "UNRESOLVED.Unknown"
    f.puts "| #{id} | #{phase} | #{family} |"
  end
end
RUBY

cat > "$out_dir/artifact-coverage-baseline.md" <<EOF
# Repository Baseline — Artifact Coverage

Generated by tools/generate-repository-baseline.sh. Presence is measured from the current filesystem; semantic completeness remains a validator task.

| Capability family | Vertical slice | Owner runtime spec | OpenAPI | Data | Events | Failure | Acceptance manifest | Evidence requirement |
|---|---|---|---|---|---|---|---|---|---|
| IDENTITY.Core | $(has_file artifacts/experience/specs/vertical-slices/identity-consent.md) | missing | missing | shared/runtime | shared | shared | $(has_file artifacts/operations/acceptance/p0-acceptance-manifest.yaml) | present in P0 manifest |
| PLACEMENT.Diagnosis | $(has_file artifacts/experience/specs/vertical-slices/placement-and-plan.md) | missing | missing | $(has_file artifacts/engineering/contracts/placement-diagnosis-contract.md) | shared | shared | $(has_file artifacts/operations/acceptance/p0-acceptance-manifest.yaml) | present in P0 manifest |
| STUDY.DailyAction | $(has_file artifacts/experience/specs/vertical-slices/daily-action.md) | missing | missing | $(has_file artifacts/engineering/contracts/daily-action-contract.md) | shared | shared | $(has_file artifacts/operations/acceptance/p0-acceptance-manifest.yaml) | present in P0 manifest |
| WRITING.Evaluation | $(has_file artifacts/experience/specs/vertical-slices/writing-task-2.md) | $(has_file artifacts/engineering/contracts/writing-task-2/runtime-spec.md) | $(has_file artifacts/engineering/contracts/writing-task-2/openapi.yaml) | $(has_file artifacts/engineering/contracts/writing-task-2/data-contract.md) | $(has_file artifacts/engineering/contracts/writing-task-2/event-contract.md) | $(has_file artifacts/engineering/contracts/writing-task-2/failure-contract.md) | $(has_file artifacts/operations/acceptance/p0-acceptance-manifest.yaml) | present; records pending |
| REVIEW.ErrorToReview | $(has_file artifacts/experience/specs/vertical-slices/error-to-review.md) | missing | missing | $(has_file artifacts/engineering/contracts/error-to-review/data-contract.md) | $(has_file artifacts/engineering/contracts/error-to-review/event-contract.md) | $(has_file artifacts/engineering/contracts/error-to-review/failure-contract.md) | $(has_file artifacts/operations/acceptance/p0-acceptance-manifest.yaml) | present in P0 manifest |
| OPS.QualityEconomics | $(has_file artifacts/experience/specs/vertical-slices/governance-ops-dashboard.md) | missing | missing | shared | $(has_file artifacts/engineering/contracts/events/event-schema-pack.md) | shared/runtime | $(has_file artifacts/operations/acceptance/p0-acceptance-manifest.yaml) | present in P0 manifest |
| READING.Practice | missing | missing | missing | missing | missing | missing | missing | missing |
| LISTENING.Practice | missing | missing | missing | missing | missing | missing | missing | missing |
| SPEAKING.Evaluation | missing | missing | missing | missing | missing | missing | missing | missing |
| PRONUNCIATION.Practice | missing | missing | missing | missing | missing | missing | missing | missing |
| MOCK.ExamSimulation | deferred | missing | missing | missing | missing | missing | missing | missing |

The table is a family-level baseline. The capability-level mapping is in capability-baseline.md.
EOF

cat > "$out_dir/family-candidate-baseline.md" <<'EOF'
# Repository Baseline — Family Candidates

Generated candidate grouping. This is not the canonical Family Registry and must be reviewed before freeze.

| Candidate family | Candidate source | Current evidence | Review decision |
|---|---|---|---|
| `IDENTITY.Core` | P0 identity profile | identity vertical slice + auth contract | pending review |
| `PLACEMENT.Diagnosis` | P0 diagnosis profile | placement vertical slice + placement contract | pending review |
| `STUDY.DailyAction` | P0 daily action profile | daily vertical slice + daily contract | pending review |
| `WRITING.Evaluation` | P0 writing evaluation profile | writing vertical slice + runtime/OpenAPI/data/event/failure contracts | pending review |
| `REVIEW.ErrorToReview` | P0 error-to-review profile | error-to-review vertical slice + contract pack | pending review |
| `OPS.QualityEconomics` | P0 quality/economics profile | governance slice + benchmark/runtime/event contracts | pending review |
| `READING.Practice` | framework/skill practice coverage | no family runtime contract | pending review |
| `LISTENING.Practice` | framework/skill practice coverage | no family runtime contract | pending review |
| `SPEAKING.Evaluation` | framework/skill practice coverage | no family runtime contract | pending review |
| `PRONUNCIATION.Practice` | framework/skill practice coverage | no family runtime contract | pending review |
| `MOCK.ExamSimulation` | framework/skill practice coverage | explicitly deferred | pending review |
EOF

cat > "$out_dir/runtime-inventory.md" <<'EOF'
# Repository Baseline — Existing Runtime Inventory

This inventory classifies existing files; it does not upgrade their readiness.

| Existing artifact | Classification | Current truth |
|---|---|---|
| `artifacts/experience/specs/vertical-slices/writing-task-2.md` | Vertical Slice | Present; product interaction/design contract |
| `artifacts/engineering/contracts/writing-task-2/runtime-spec.md` | Runtime Candidate | Present; evidence and release gates still pending |
| `artifacts/engineering/contracts/writing-task-2/openapi.yaml` | API Contract | Present; Writing-only |
| `artifacts/engineering/contracts/multi-skill-practice/runtime-spec.md` | Shared Candidate | Candidate scaffold; not a per-family owner runtime spec |
| `artifacts/experience/specs/skill-practice-coverage.md` | Coverage Contract | Inventory/projection; not implementation definition |
| `artifacts/operations/capability-manifest.yaml` | P0 Projection Seed | Not source of truth |
| `artifacts/operations/catalogs/capability-index.md` | Generated Projection | 180 IDs; not source of truth |
EOF

cat > "$out_dir/authority-drift-report.md" <<'EOF'
# Repository Baseline — Authority Drift

Generated/recorded baseline findings requiring resolution before registry freeze.

| Finding | Severity | Evidence | Disposition |
|---|---|---|---|
| Family Registry currently points `owner_spec` to vertical slices rather than dedicated Owner Runtime Specs | P1 | `artifacts/operations/capability-family-registry.yaml` | fix before Phase 5 completion |
| Family Registry and Delta Registry scope authority must remain limited to implementation identity/variation | P1 | registry headers + architecture freeze | enforce with validator |
| Capability phase projection uses P0/P1/P2/deferred rather than normalized lifecycle | P1 | `capability-phase-index.md` | normalize in lifecycle registry |
| Existing runtime/API coverage is Writing-centric | P1 | runtime inventory and artifact coverage baseline | truthful; do not upgrade without contracts |
| Generated catalog projections are not capability implementation definitions | P1 | capability index/phase index headers | preserve projection label |
EOF

cat > "$out_dir/README.md" <<'EOF'
# Repository Baseline

Generated by `tools/generate-repository-baseline.sh`.

These reports are Phase -1 diagnostics. They are not sources of truth and must not be edited to improve coverage. Canonical decisions begin only after baseline review and lifecycle/family freeze.
EOF

outputs=(
  capability-baseline.md
  artifact-coverage-baseline.md
  family-candidate-baseline.md
  runtime-inventory.md
  authority-drift-report.md
  README.md
)
stale=0
for file in "${outputs[@]}"; do
  if ! cmp -s "$out_dir/$file" "$target_dir/$file"; then
    stale=1
    if ! $check; then
      mv "$out_dir/$file" "$target_dir/$file"
    fi
  fi
done

if $check; then
  if (( stale )); then
    echo "repository baseline projections are stale; run tools/generate-repository-baseline.sh" >&2
    exit 1
  fi
  echo "repository baseline projections are current"
elif (( stale )); then
  echo "repository baseline generated: $target_dir"
else
  echo "repository baseline unchanged"
fi
